---

- name: Install redis common dependencies
  become: true
  apt:
    name: "{{ item.name }}"
    state: present
  when: redis_dependencies is defined
  with_items: redis_dependencies
  tags:
    - apt
    - dependencies

- name: Install redis packages via pip
  become: true
  pip: name="{{ item.name }}" state="{{ item.state}}"
  when: redis_pip_packages is defined
  with_items: redis_pip_packages